<?php
return [
    [
        "id"          => 1,
        "name"        => "Anatra alla pechinese 1",
        "image"       => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/79/47/35/tien-tsin.jpg?w=600&h=400&s=1",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 3,
    ],
    [
        "id"          => 2,
        "name"        => "Anatra alla pechinese 2",
        "image"       => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/79/47/35/tien-tsin.jpg?w=600&h=400&s=1",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 3,
    ],
    [
        "id"          => 3,
        "name"        => "Anatra alla pechinese 3",
        "image"       => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/79/47/35/tien-tsin.jpg?w=600&h=400&s=1",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 3,
    ],
    [
        "id"          => 4,
        "name"        => "Anatra alla pechinese 4",
        "image"       => "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/79/47/35/tien-tsin.jpg?w=600&h=400&s=1",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 3,
    ],
    [
        "id"          => 5,
        "name"        => "Sushi assortito 1",
        "image"       => "https://t1.pixers.pics/img-c676e9e9/poster-menu-di-sushi-assortiti-con-salmone-cucina-giapponese.jpg?H4sIAAAAAAAAA42PTW7EIAyFr5NIJHYgjCEHmO0cIYJApmnzg4C2o56-pK26q1R54WfL77MevO7JzB4mv2cfYVucWz3My1qmNESflg9fSS0Y1kPZrhViUcebj1M8QtUIwZpOcHbhxCRX9fBuinMz8aV6yjmkASCJNiyPgittSjBtCTh2BKhAamUmbx3pzvAxNCmb3ZnoGsKGHhLbsN8ZnvV_sIIOQVrX2YtVDnurRs6xwJpfwhe2R2I9qRP9E5MQGZ3xcly2quQ9ynWunsO9hj9-fmsoLrjegERJBBpByHM1Xm8kpNYo5DijniX2Ughj0c_SO66nuSdnyXW9o7Z8-QQBuowBjAEAAA==",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 4,
    ],
    [
        "id"          => 6,
        "name"        => "Sushi assortito 2",
        "image"       => "https://t1.pixers.pics/img-c676e9e9/poster-menu-di-sushi-assortiti-con-salmone-cucina-giapponese.jpg?H4sIAAAAAAAAA42PTW7EIAyFr5NIJHYgjCEHmO0cIYJApmnzg4C2o56-pK26q1R54WfL77MevO7JzB4mv2cfYVucWz3My1qmNESflg9fSS0Y1kPZrhViUcebj1M8QtUIwZpOcHbhxCRX9fBuinMz8aV6yjmkASCJNiyPgittSjBtCTh2BKhAamUmbx3pzvAxNCmb3ZnoGsKGHhLbsN8ZnvV_sIIOQVrX2YtVDnurRs6xwJpfwhe2R2I9qRP9E5MQGZ3xcly2quQ9ynWunsO9hj9-fmsoLrjegERJBBpByHM1Xm8kpNYo5DijniX2Ughj0c_SO66nuSdnyXW9o7Z8-QQBuowBjAEAAA==",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 4,
    ],
    [
        "id"          => 7,
        "name"        => "Sushi assortito 3",
        "image"       => "https://t1.pixers.pics/img-c676e9e9/poster-menu-di-sushi-assortiti-con-salmone-cucina-giapponese.jpg?H4sIAAAAAAAAA42PTW7EIAyFr5NIJHYgjCEHmO0cIYJApmnzg4C2o56-pK26q1R54WfL77MevO7JzB4mv2cfYVucWz3My1qmNESflg9fSS0Y1kPZrhViUcebj1M8QtUIwZpOcHbhxCRX9fBuinMz8aV6yjmkASCJNiyPgittSjBtCTh2BKhAamUmbx3pzvAxNCmb3ZnoGsKGHhLbsN8ZnvV_sIIOQVrX2YtVDnurRs6xwJpfwhe2R2I9qRP9E5MQGZ3xcly2quQ9ynWunsO9hj9-fmsoLrjegERJBBpByHM1Xm8kpNYo5DijniX2Ughj0c_SO66nuSdnyXW9o7Z8-QQBuowBjAEAAA==",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 4,
    ],
    [
        "id"          => 8,
        "name"        => "Sushi assortito 4",
        "image"       => "https://t1.pixers.pics/img-c676e9e9/poster-menu-di-sushi-assortiti-con-salmone-cucina-giapponese.jpg?H4sIAAAAAAAAA42PTW7EIAyFr5NIJHYgjCEHmO0cIYJApmnzg4C2o56-pK26q1R54WfL77MevO7JzB4mv2cfYVucWz3My1qmNESflg9fSS0Y1kPZrhViUcebj1M8QtUIwZpOcHbhxCRX9fBuinMz8aV6yjmkASCJNiyPgittSjBtCTh2BKhAamUmbx3pzvAxNCmb3ZnoGsKGHhLbsN8ZnvV_sIIOQVrX2YtVDnurRs6xwJpfwhe2R2I9qRP9E5MQGZ3xcly2quQ9ynWunsO9hj9-fmsoLrjegERJBBpByHM1Xm8kpNYo5DijniX2Ughj0c_SO66nuSdnyXW9o7Z8-QQBuowBjAEAAA==",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 4,
    ],
    [
        "id"          => 9,
        "name"        => "Hamburger Classico 1",
        "image"       => "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 8,
    ],
    [
        "id"          => 10,
        "name"        => "Hamburger Classico 2",
        "image"       => "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 8,
    ],
    [
        "id"          => 11,
        "name"        => "Hamburger Classico 3",
        "image"       => "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 8,
    ],
    [
        "id"          => 12,
        "name"        => "Hamburger Classico 4",
        "image"       => "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRRto3IlY56MlAIOAvXHvPEVxBDVzG1uz1zULEBYdJ-I4Aa-xOyPEVvv7fmIjLnxaOz",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 8,
    ],
    [
        "id"          => 13,
        "name"        => "Chicken Tikka Masala 1",
        "image"       => "https://www.allrecipes.com/thmb/1ul-jdOz8H4b6BDrRcYOuNmJgt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/239867chef-johns-chicken-tikka-masala-ddmfs-3X4-0572-e02a25f8c7b745459a9106e9eb13de10.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 9,
    ],
    [
        "id"          => 14,
        "name"        => "Chicken Tikka Masala 2",
        "image"       => "https://www.allrecipes.com/thmb/1ul-jdOz8H4b6BDrRcYOuNmJgt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/239867chef-johns-chicken-tikka-masala-ddmfs-3X4-0572-e02a25f8c7b745459a9106e9eb13de10.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 9,
    ],
    [
        "id"          => 15,
        "name"        => "Chicken Tikka Masala 3",
        "image"       => "https://www.allrecipes.com/thmb/1ul-jdOz8H4b6BDrRcYOuNmJgt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/239867chef-johns-chicken-tikka-masala-ddmfs-3X4-0572-e02a25f8c7b745459a9106e9eb13de10.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 9,
    ],
    [
        "id"          =>16,
        "name"        => "Chicken Tikka Masala 4",
        "image"       => "https://www.allrecipes.com/thmb/1ul-jdOz8H4b6BDrRcYOuNmJgt4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/239867chef-johns-chicken-tikka-masala-ddmfs-3X4-0572-e02a25f8c7b745459a9106e9eb13de10.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 9,
    ],
    [
        "id"          => 17,
        "name"        => "Spaghetti alla Carbonara 1",
        "image"       => "https://www.allrecipes.com/thmb/Vg2cRidr2zcYhWGvPD8M18xM_WY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-ii-DDMFS-4x3-6edea51e421e4457ac0c3269f3be5157.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 1,
    ],
    [
        "id"          => 18,
        "name"        => "Spaghetti alla Carbonara 2",
        "image"       => "https://www.allrecipes.com/thmb/Vg2cRidr2zcYhWGvPD8M18xM_WY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-ii-DDMFS-4x3-6edea51e421e4457ac0c3269f3be5157.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 1,
    ],
    [
        "id"          => 19,
        "name"        => "Spaghetti alla Carbonara 3",
        "image"       => "https://www.allrecipes.com/thmb/Vg2cRidr2zcYhWGvPD8M18xM_WY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-ii-DDMFS-4x3-6edea51e421e4457ac0c3269f3be5157.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 1,
    ],
    [
        "id"          => 20,
        "name"        => "Spaghetti alla Carbonara 4",
        "image"       => "https://www.allrecipes.com/thmb/Vg2cRidr2zcYhWGvPD8M18xM_WY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/11973-spaghetti-carbonara-ii-DDMFS-4x3-6edea51e421e4457ac0c3269f3be5157.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 1,
    ],
    [
        "id"          => 21,
        "name"        => "Enchiladas 1",
        "image"       => "https://www.goya.com/media/4080/beef-enchiladas.jpg?quality=80",
        "description" => "Tortillas di mais ripiene di pollo cotto, avvolte e coperte con salsa di pomodoro e formaggio, quindi cotte al forno fino a doratura.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 7,
    ],
    [
        "id"          => 22,
        "name"        => "Enchiladas 2",
        "image"       => "https://www.goya.com/media/4080/beef-enchiladas.jpg?quality=80",
        "description" => "Tortillas di mais ripiene di pollo cotto, avvolte e coperte con salsa di pomodoro e formaggio, quindi cotte al forno fino a doratura.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 7,
    ],
    [
        "id"          => 23,
        "name"        => "Enchiladas 3",
        "image"       => "https://www.goya.com/media/4080/beef-enchiladas.jpg?quality=80",
        "description" => "Tortillas di mais ripiene di pollo cotto, avvolte e coperte con salsa di pomodoro e formaggio, quindi cotte al forno fino a doratura.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 7,
    ],
    [
        "id"          => 24,
        "name"        => "Enchiladas 4",
        "image"       => "https://www.goya.com/media/4080/beef-enchiladas.jpg?quality=80",
        "description" => "Tortillas di mais ripiene di pollo cotto, avvolte e coperte con salsa di pomodoro e formaggio, quindi cotte al forno fino a doratura.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 7,
    ],
    [
        "id"          => 25,
        "name"        => "Pizza Margherita 1",
        "image"       => "https://it.ooni.com/cdn/shop/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 2,
    ],
    [
        "id"          => 26,
        "name"        => "Pizza Margherita 2",
        "image"       => "https://it.ooni.com/cdn/shop/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 2,
    ],
    [
        "id"          => 27,
        "name"        => "Pizza Margherita 3",
        "image"       => "https://it.ooni.com/cdn/shop/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 2,
    ],
    [
        "id"          => 28,
        "name"        => "Pizza Margherita 4",
        "image"       => "https://it.ooni.com/cdn/shop/articles/Margherita-9920.jpg?crop=center&height=800&v=1644590028&width=800",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
        "restaurant_id" => 2,
    ],
    [
        "id" => 29,
        "name" => "Moussaka 1",
        "image" => "https://www.mygreekdish.com/wp-content/uploads/2013/05/Moussaka-recipe-Traditional-Greek-Moussaka-with-Eggplants.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 5,
    ],
    [
        "id" => 30,
        "name" => "Moussaka 2",
        "image" => "https://www.mygreekdish.com/wp-content/uploads/2013/05/Moussaka-recipe-Traditional-Greek-Moussaka-with-Eggplants.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 5,
    ],
    [
        "id" => 31,
        "name" => "Moussaka 3",
        "image" => "https://www.mygreekdish.com/wp-content/uploads/2013/05/Moussaka-recipe-Traditional-Greek-Moussaka-with-Eggplants.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 5,
    ],
    [
        "id" => 32,
        "name" => "Moussaka 4",
        "image" => "https://www.mygreekdish.com/wp-content/uploads/2013/05/Moussaka-recipe-Traditional-Greek-Moussaka-with-Eggplants.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 5,
    ],
    [
        "id" => 33,
        "name" => "Poke classico 1",
        "image" => "https://www.leitv.it/wp-content/uploads/2019/07/poke-bowl.jpg?v=100569",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 6,
    ],
    [
        "id" => 34,
        "name" => "Poke classico 2",
        "image" => "https://www.leitv.it/wp-content/uploads/2019/07/poke-bowl.jpg?v=100569",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 6,
    ],
    [
        "id" => 35,
        "name" => "Poke classico 3",
        "image" => "https://www.leitv.it/wp-content/uploads/2019/07/poke-bowl.jpg?v=100569",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 6,
    ],
    [
        "id" => 36,
        "name" => "Poke classico 4",
        "image" => "https://www.leitv.it/wp-content/uploads/2019/07/poke-bowl.jpg?v=100569",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 6,
    ],
    [
        "id" => 37,
        "name" => "Tiramisù 1",
        "image" => "https://www.giallozafferano.it/images/173-17354/Tiramisu_650x433_wm.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 10,
    ],
    [
        "id" => 38,
        "name" => "Tiramisù 2",
        "image" => "https://www.giallozafferano.it/images/173-17354/Tiramisu_650x433_wm.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 10,
    ],
    [
        "id" => 39,
        "name" => "Tiramisù 3",
        "image" => "https://www.giallozafferano.it/images/173-17354/Tiramisu_650x433_wm.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 10,
    ],
    [
        "id" => 40,
        "name" => "Tiramisù 4",
        "image" => "https://www.giallozafferano.it/images/173-17354/Tiramisu_650x433_wm.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
        "restaurant_id" => 10,
    ],
];
