<?php
return [
    [
        "id"          => 1,
        "restaurant_id"=> 2,
        "name"        => "Anatra alla pechinese 1",
        "image" => "meal_images/Anatra_alla_pechinese.jpg",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 2,
        "restaurant_id"=> 2,
        "name"        => "Anatra alla pechinese 2",
        "image" => "meal_images/Anatra_alla_pechinese.jpg",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 3,
        "restaurant_id"=> 2,
        "name"        => "Anatra alla pechinese 3",
        "image" => "meal_images/Anatra_alla_pechinese.jpg",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 4,
        "restaurant_id"=> 2,
        "name"        => "Anatra alla pechinese 4",
        "image" => "meal_images/Anatra_alla_pechinese.jpg",
        "description" => "Un piatto classico cinese con anatra arrosto servita con sottile pancake, salsa di prugne e julienne di cipolla verde.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 5,
        "restaurant_id"=> 3,
        "name"        => "Sushi assortito 1",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 6,
        "restaurant_id"=> 3,
        "name"        => "Sushi assortito 2",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 7,
        "restaurant_id"=> 3,
        "name"        => "Sushi assortito 3",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 8,
        "restaurant_id"=> 3,
        "name"        => "Sushi assortito 4",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Un assortimento di sushi giapponese fresco e prelibato, che include nigiri (topped di pesce su un piccolo blocco di riso) e maki (rotoli di riso avvolti in alga nori).",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 9,
        "restaurant_id"=> 1,
        "name"        => "Chicken Alfredo 1",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 10,
        "restaurant_id"=> 1,
        "name"        => "Chicken Alfredo 2",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 11,
        "restaurant_id"=> 1,
        "name"        => "Chicken Alfredo 3",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 12,
        "restaurant_id"=> 1,
        "name"        => "Chicken Alfredo 4",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 13,
        "restaurant_id"=> 4,
        "name"        => "Enchiladas 1",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Enchiladas",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 14,
        "restaurant_id"=> 4,
        "name"        => "Enchiladas 2",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Enchiladas.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 15,
        "restaurant_id"=> 4,
        "name"        => "Enchiladas 3",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Enchiladas.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 16,
        "restaurant_id"=> 4,
        "name"        => "Enchiladas 4",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Enchiladas.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 17,
        "restaurant_id"=> 5,
        "name"        => "Moussaka 1",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 18,
        "restaurant_id"=> 5,
        "name"        => "Moussaka 2",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 19,
        "restaurant_id"=> 5,
        "name"        => "Moussaka 3",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 20,
        "restaurant_id"=> 5,
        "name"        => "Moussaka 4",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Un piatto tradizionale greco a base di melanzane, carne macinata, besciamella e patate.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 21,
        "restaurant_id"=> 6,
        "name"        => "Indian Dish 1",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Indian Dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 22,
        "restaurant_id"=> 6,
        "name"        => "Indian Dish 2",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Indian Dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 23,
        "restaurant_id"=> 6,
        "name"        => "Indian Dish 3",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Indian Dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 24,
        "restaurant_id"=> 6,
        "name"        => "Indian Dish 4",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Indian Dish.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 25,
        "restaurant_id"=> 7,
        "name"        => "Pizza Margherita 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 26,
        "restaurant_id"=> 7,
        "name"        => "Pizza Margherita 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 27,
        "restaurant_id"=> 7,
        "name"        => "Pizza Margherita 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id"          => 28,
        "restaurant_id"=> 7,
        "name"        => "Pizza Margherita 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price"       => 20,
        "available"   => 1,
    ],
    [
        "id" => 29,
	    "restaurant_id" => 8,
        "name" => "BBQ Pulled Pork Sandwich 1",
        "image" => "meal_images/pork.jpg",
        "description" => "BBQ Pulled Pork Sandwich.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 30,
	    "restaurant_id" => 8,
        "name" => "BBQ Pulled Pork Sandwich 2",
        "image" => "meal_images/pork.jpg",
        "description" => "BBQ Pulled Pork Sandwich.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 31,
	    "restaurant_id" => 8,
        "name" => "BBQ Pulled Pork Sandwich 3",
        "image" => "meal_images/pork.jpg",
        "description" => "BBQ Pulled Pork Sandwich.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 32,
	    "restaurant_id" => 8,
        "name" => "BBQ Pulled Pork Sandwich 4",
        "image" => "meal_images/pork.jpg",
        "description" => "BBQ Pulled Pork Sandwich.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 33,
	    "restaurant_id" => 9,
        "name" => "Poke classico 1",
        "image" => "meal_images/Poke_classico.jpg",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 34,
	    "restaurant_id" => 9,
        "name" => "Poke classico 2",
        "image" => "meal_images/Poke_classico.jpg",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 35,
	    "restaurant_id" => 9,
        "name" => "Poke classico 3",
        "image" => "meal_images/Poke_classico.jpg",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 36,
	    "restaurant_id" => 9,
        "name" => "Poke classico 4",
        "image" => "meal_images/Poke_classico.jpg",
        "description" => "Base di riso con salmone, tonno, avocado, cetriolo, edamame e salsa di soia.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 37,
	    "restaurant_id" => 10,
        "name" => "Tiramisù 1",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 38,
	    "restaurant_id" => 10,
        "name" => "Tiramisù 2",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 39,
	    "restaurant_id" => 10,
        "name" => "Tiramisù 3",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 40,
	    "restaurant_id" => 10,
        "name" => "Tiramisù 4",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 41,
        "restaurant_id" => 11,
        "name" => "Spaghetti alla Carbonara 1",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 42,
        "restaurant_id" => 11,
        "name" => "Spaghetti alla Carbonara 2",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 43,
        "restaurant_id" => 11,
        "name" => "Spaghetti alla Carbonara 3",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 44,
        "restaurant_id" => 11,
        "name" => "Spaghetti alla Carbonara 4",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "Gli spaghetti alla carbonara sono un piatto tradizionale romano. Gli ingredienti principali includono uova, pancetta, pecorino romano, pepe nero e spaghetti.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 45,
        "restaurant_id" => 12,
        "name" => "Caesar Salad 1",
        "image" => "meal_images/ceasar.jpg",
        "description" => "Insalata con cuori di lattuga romana, crostini di pane, parmigiano grattugiato, uova sode e salsa Caesar. Un classico della cucina internazionale.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 46,
        "restaurant_id" => 12,
        "name" => "Caesar Salad 2",
        "image" => "meal_images/ceasar.jpg",
        "description" => "Insalata con cuori di lattuga romana, crostini di pane, parmigiano grattugiato, uova sode e salsa Caesar. Un classico della cucina internazionale.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 47,
        "restaurant_id" => 12,
        "name" => "Caesar Salad 3",
        "image" => "meal_images/ceasar.jpg",
        "description" => "Insalata con cuori di lattuga romana, crostini di pane, parmigiano grattugiato, uova sode e salsa Caesar. Un classico della cucina internazionale.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 48,
        "restaurant_id" => 12,
        "name" => "Caesar Salad 4",
        "image" => "meal_images/ceasar.jpg",
        "description" => "Insalata con cuori di lattuga romana, crostini di pane, parmigiano grattugiato, uova sode e salsa Caesar. Un classico della cucina internazionale.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 49,
        "restaurant_id" => 13,
        "name" => "Hamburger 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 50,
        "restaurant_id" => 13,
        "name" => "Hamburger 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 51,
        "restaurant_id" => 13,
        "name" => "Hamburger 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 52,
        "restaurant_id" => 13,
        "name" => "Hamburger 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 53,
        "restaurant_id" => 14,
        "name" => "Pad Thai 1",
        "image" => "meal_images/thai.jpg",
        "description" => "Noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 54,
        "restaurant_id" => 14,
        "name" => "Pad Thai 2",
        "image" => "meal_images/thai.jpg",
        "description" => "Noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 55,
        "restaurant_id" => 14,
        "name" => "Pad Thai 3",
        "image" => "meal_images/thai.jpg",
        "description" => "Noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 56,
        "restaurant_id" => 14,
        "name" => "Pad Thai 4",
        "image" => "meal_images/thai.jpg",
        "description" => "Noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 57,
        "restaurant_id" => 15,
        "name" => "Gyudon 1",
        "image" => "meal_images/thai.jpg",
        "description" => "Riso coperto con uno stufato di manzo cotto lentamente in una miscela di salsa di soia, mirin e zucchero. Una specialità giapponese.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 58,
        "restaurant_id" => 15,
        "name" => "Gyudon 2",
        "image" => "meal_images/thai.jpg",
        "description" => "Riso coperto con uno stufato di manzo cotto lentamente in una miscela di salsa di soia, mirin e zucchero. Una specialità giapponese.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 59,
        "restaurant_id" => 15,
        "name" => "Gyudon 3",
        "image" => "meal_images/thai.jpg",
        "description" => "Riso coperto con uno stufato di manzo cotto lentamente in una miscela di salsa di soia, mirin e zucchero. Una specialità giapponese.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 60,
        "restaurant_id" => 15,
        "name" => "Gyudon 4",
        "image" => "meal_images/thai.jpg",
        "description" => "Riso coperto con uno stufato di manzo cotto lentamente in una miscela di salsa di soia, mirin e zucchero. Una specialità giapponese.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 61,
        "restaurant_id" => 16,
        "name" => "Escargot 1",
        "image" => "meal_images/escargots.png",
        "description" => "Gli escargot, una prelibatezza gastronomica francese, presentano lumache di terra cotte al burro all'aglio e prezzemolo.",
        "price" => 17.00,
        "available" => 1,
    ],
    [
        "id" => 62,
        "restaurant_id" => 16,
        "name" => "Escargot 2",
        "image" => "meal_images/escargots.png",
        "description" => "Gli escargot, una prelibatezza gastronomica francese, presentano lumache di terra cotte al burro all'aglio e prezzemolo.",
        "price" => 17.00,
        "available" => 1,
    ],
    [
        "id" => 63,
        "restaurant_id" => 16,
        "name" => "Escargot 3",
        "image" => "meal_images/escargots.png",
        "description" => "Gli escargot, una prelibatezza gastronomica francese, presentano lumache di terra cotte al burro all'aglio e prezzemolo.",
        "price" => 17.00,
        "available" => 1,
    ],
    [
        "id" => 64,
        "restaurant_id" => 16,
        "name" => "Escargot 4",
        "image" => "meal_images/escargots.png",
        "description" => "Gli escargot, una prelibatezza gastronomica francese, presentano lumache di terra cotte al burro all'aglio e prezzemolo..",
        "price" => 17.00,
        "available" => 1,
    ],
    [
        "id" => 65,
        "restaurant_id" => 17,
        "name" => "Pizza Margherita 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 66,
        "restaurant_id" => 17,
        "name" => "Pizza Margherita 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 67,
        "restaurant_id" => 17,
        "name" => "Pizza Margherita 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 68,
        "restaurant_id" => 17,
        "name" => "Pizza Margherita 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 69,
        "restaurant_id" => 18,
        "name" => "Hamburger Classico 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 70,
        "restaurant_id" => 18,
        "name" => "Hamburger Classico 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 71,
        "restaurant_id" => 18,
        "name" => "Hamburger Classico 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 72,
        "restaurant_id" => 18,
        "name" => "Hamburger Classico 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 73,
        "restaurant_id" => 19,
        "name" => "Gamberi e frutti di mare 1",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Un piatto irresistibile di gamberi e frutti di mare, dove la freschezza del mare si sposa con la dolcezza dei gamberi",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 74,
        "restaurant_id" => 19,
        "name" => "Gamberi e frutti di mare 2",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Un piatto irresistibile di gamberi e frutti di mare, dove la freschezza del mare si sposa con la dolcezza dei gamberi.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 75,
        "restaurant_id" => 19,
        "name" => "Gamberi e frutti di mare 3",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Un piatto irresistibile di gamberi e frutti di mare, dove la freschezza del mare si sposa con la dolcezza dei gamberi.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 76,
        "restaurant_id" => 19,
        "name" => "Gamberi e frutti di mare 4",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Un piatto irresistibile di gamberi e frutti di mare, dove la freschezza del mare si sposa con la dolcezza dei gamberi.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 77,
        "restaurant_id" => 20,
        "name" => "Gelato 1",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 78,
        "restaurant_id" => 20,
        "name" => "Gelato 2",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 79,
        "restaurant_id" => 20,
        "name" => "Gelato 3",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 80,
        "restaurant_id" => 20,
        "name" => "Gelato 4",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 81,
        "restaurant_id" => 21,
        "name" => "Hamburger Classico 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 82,
        "restaurant_id" => 21,
        "name" => "Hamburger Classico 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 83,
        "restaurant_id" => 21,
        "name" => "Hamburger Classico 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 84,
        "restaurant_id" => 21,
        "name" => "Hamburger Classico 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 85,
        "restaurant_id" => 22,
        "name" => "Pho 1",
        "image" => "meal_images/pho.jpg",
        "description" => "Zuppa vietnamita con noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 86,
        "restaurant_id" => 22,
        "name" => "Pho 2",
        "image" => "meal_images/pho.jpg",
        "description" => "Zuppa vietnamita con noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 87,
        "restaurant_id" => 22,
        "name" => "Pho 3",
        "image" => "meal_images/pho.jpg",
        "description" => "Zuppa vietnamita con noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 88,
        "restaurant_id" => 22,
        "name" => "Pho 4",
        "image" => "meal_images/pho.jpg",
        "description" => "Zuppa vietnamita con noodles di riso, brodo di carne, erbe aromatiche e fettine di manzo. Un comfort food delizioso.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 89,
        "restaurant_id" => 23,
        "name" => "Gnocchi al pesto 1",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 90,
        "restaurant_id" => 23,
        "name" => "Gnocchi al pesto 2",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 91,
        "restaurant_id" => 23,
        "name" => "Gnocchi al pesto 3",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 92,
        "restaurant_id" => 23,
        "name" => "Gnocchi al pesto 4",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 93,
        "restaurant_id" => 24,
        "name" => "Cevice 1",
        "image" => "meal_images/ceviche.jpg",
        "description" => "Pesce crudo marinato in succo di lime con cipolla, peperoncino, coriandolo e aguacate. Un'opzione fresca e gustosa della cucina peruviana.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 94,
        "restaurant_id" => 24,
        "name" => "Cevice 2",
        "image" => "meal_images/ceviche.jpg",
        "description" => "Pesce crudo marinato in succo di lime con cipolla, peperoncino, coriandolo e aguacate. Un'opzione fresca e gustosa della cucina peruviana.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 95,
        "restaurant_id" => 24,
        "name" => "Cevice 3",
        "image" => "meal_images/ceviche.jpg",
        "description" => "Pesce crudo marinato in succo di lime con cipolla, peperoncino, coriandolo e aguacate. Un'opzione fresca e gustosa della cucina peruviana.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 96,
        "restaurant_id" => 24,
        "name" => "Cevice 4",
        "image" => "meal_images/ceviche.jpg",
        "description" => "Pesce crudo marinato in succo di lime con cipolla, peperoncino, coriandolo e aguacate. Un'opzione fresca e gustosa della cucina peruviana.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 97,
        "restaurant_id" => 25,
        "name" => "Ratatouille 1",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 98,
        "restaurant_id" => 25,
        "name" => "Ratatouille 2",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 99,
        "restaurant_id" => 25,
        "name" => "Ratatouille 3",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 100,
        "restaurant_id" => 25,
        "name" => "Ratatouille 4",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 101,
        "restaurant_id" => 26,
        "name" => "Pizza Margherita 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 102,
        "restaurant_id" => 26,
        "name" => "Pizza Margherita 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 103,
        "restaurant_id" => 26,
        "name" => "Pizza Margherita 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 104,
        "restaurant_id" => 26,
        "name" => "Pizza Margherita 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 105,
        "restaurant_id" => 27,
        "name" => "Pad Thai 1",
        "image" => "meal_images/thai.jpg",
        "description" => "Stir-fried rice noodles with tofu, shrimp, peanuts, bean sprouts, and lime. A popular Thai street food dish with a perfect balance of flavors.",
        "price" => 25.00,
        "available" => 1,
    ],
    [
        "id" => 106,
        "restaurant_id" => 27,
        "name" => "Pad Thai 2",
        "image" => "meal_images/thai.jpg",
        "description" => "Stir-fried rice noodles with tofu, shrimp, peanuts, bean sprouts, and lime. A popular Thai street food dish with a perfect balance of flavors..",
        "price" => 25.00,
        "available" => 1,
    ],
    [
        "id" => 107,
        "restaurant_id" => 27,
        "name" => "Pad Thai 3",
        "image" => "meal_images/thai.jpg",
        "description" => "Stir-fried rice noodles with tofu, shrimp, peanuts, bean sprouts, and lime. A popular Thai street food dish with a perfect balance of flavors.",
        "price" => 25.00,
        "available" => 1,
    ],
    [
        "id" => 108,
        "restaurant_id" => 27,
        "name" => "Pad Thai 4",
        "image" => "meal_images/thai.jpg",
        "description" => "Stir-fried rice noodles with tofu, shrimp, peanuts, bean sprouts, and lime. A popular Thai street food dish with a perfect balance of flavors.",
        "price" => 25.00,
        "available" => 1,
    ],
    [
        "id" => 109,
        "restaurant_id" => 28,
        "name" => "Chicken Alfredo 1",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 110,
        "restaurant_id" => 28,
        "name" => "Chicken Alfredo 2",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 111,
        "restaurant_id" => 28,
        "name" => "Chicken Alfredo 3",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 112,
        "restaurant_id" => 28,
        "name" => "Chicken Alfredo 4",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta in a creamy Alfredo sauce with grilled chicken. A rich and indulgent Italian pasta dish.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 113,
        "restaurant_id" => 29,
        "name" => "Shrimp Scampi 1",
        "image" => "meal_images/seafood.jpg",
        "description" => "Large shrimp sautéed in garlic, butter, white wine, and lemon juice, served over pasta. A classic Italian-American seafood dish.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 114,
        "restaurant_id" => 29,
        "name" => "Shrimp Scampi 2",
        "image" => "meal_images/seafood.jpg",
        "description" => "Large shrimp sautéed in garlic, butter, white wine, and lemon juice, served over pasta. A classic Italian-American seafood dish.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 115,
        "restaurant_id" => 29,
        "name" => "Shrimp Scampi 3",
        "image" => "meal_images/seafood.jpg",
        "description" => "Large shrimp sautéed in garlic, butter, white wine, and lemon juice, served over pasta. A classic Italian-American seafood dish.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 116,
        "restaurant_id" => 29,
        "name" => "Shrimp Scampi 4",
        "image" => "meal_images/seafood.jpg",
        "description" => "Large shrimp sautéed in garlic, butter, white wine, and lemon juice, served over pasta. A classic Italian-American seafood dish.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 117,
        "restaurant_id" => 30,
        "name" => "Tiramisù 1",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 118,
        "restaurant_id" => 30,
        "name" => "Tiramisù 2",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 119,
        "restaurant_id" => 30,
        "name" => "Tiramisù 3",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 120,
        "restaurant_id" => 30,
        "name" => "Tiramisù 4",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 121,
        "restaurant_id" => 31,
        "name" => "Caprese 1",
        "image" => "meal_images/caprese.jpg",
        "description" => "Insalata fresca con pomodori, mozzarella di bufala, basilico fresco, olio d'oliva e sale. Un'opzione leggera e gustosa.",
        "price" => 28.00,
        "available" => 1,
    ],
    [
        "id" => 122,
        "restaurant_id" => 31,
        "name" => "Caprese 2",
        "image" => "meal_images/caprese.jpg",
        "description" => "Insalata fresca con pomodori, mozzarella di bufala, basilico fresco, olio d'oliva e sale. Un'opzione leggera e gustosa.",
        "price" => 28.00,
        "available" => 1,
    ],
    [
        "id" => 123,
        "restaurant_id" => 31,
        "name" => "Caprese 3",
        "image" => "meal_images/caprese.jpg",
        "description" => "Insalata fresca con pomodori, mozzarella di bufala, basilico fresco, olio d'oliva e sale. Un'opzione leggera e gustosa.",
        "price" => 28.00,
        "available" => 1,
    ],
    [
        "id" => 124,
        "restaurant_id" => 31,
        "name" => "Caprese 4",
        "image" => "meal_images/caprese.jpg",
        "description" => "Insalata fresca con pomodori, mozzarella di bufala, basilico fresco, olio d'oliva e sale. Un'opzione leggera e gustosa.",
        "price" => 28.00,
        "available" => 1,
    ],
    [
        "id" => 125,
        "restaurant_id" => 32,
        "name" => "Sushi Assortito 1",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Grilled salmon glazed with a savory teriyaki sauce, served with steamed rice and vegetables. A delicious Japanese dish.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 126,
        "restaurant_id" => 32,
        "name" => "Sushi Assortito 2",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Grilled salmon glazed with a savory teriyaki sauce, served with steamed rice and vegetables. A delicious Japanese dish.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 127,
        "restaurant_id" => 32,
        "name" => "Sushi Assortito 3",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Grilled salmon glazed with a savory teriyaki sauce, served with steamed rice and vegetables. A delicious Japanese dish.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 128,
        "restaurant_id" => 32,
        "name" => "Sushi Assortito 4",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Grilled salmon glazed with a savory teriyaki sauce, served with steamed rice and vegetables. A delicious Japanese dish.",
        "price" => 19.00,
        "available" => 1,
    ],
    [
        "id" => 129,
        "restaurant_id" => 33,
        "name" => "Hamburger 1",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 130,
        "restaurant_id" => 33,
        "name" => "Hamburger 2",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 131,
        "restaurant_id" => 33,
        "name" => "Hamburger 3",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 132,
        "restaurant_id" => 33,
        "name" => "Hamburger 4",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 21.00,
        "available" => 1,
    ],
    [
        "id" => 133,
        "restaurant_id" => 34,
        "name" => "Thai 1",
        "image" => "meal_images/thai.jpg",
        "description" => "A Thai stir-fried noodle dish made with rice noodles, tofu or shrimp, bean sprouts, peanuts, lime, and chili.

",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 134,
        "restaurant_id" => 34,
        "name" => "Thai 2",
        "image" => "meal_images/thai.jpg",
        "description" => "A Thai stir-fried noodle dish made with rice noodles, tofu or shrimp, bean sprouts, peanuts, lime, and chili.

",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 135,
        "restaurant_id" => 34,
        "name" => "Thai 3",
        "image" => "meal_images/thai.jpg",
        "description" => "A Thai stir-fried noodle dish made with rice noodles, tofu or shrimp, bean sprouts, peanuts, lime, and chili.

",
        "price" => 23.00,
        "available" => 1,
    ],
    [
        "id" => 136,
        "restaurant_id" => 35,
        "name" => "Tacos al Pastor 1",
        "image" => "meal_images/tacos.jpg",
        "description" => "Mexican street tacos with marinated and spit-grilled pork, pineapple, onions, and cilantro.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 137,
        "restaurant_id" => 35,
        "name" => "Tacos al Pastor 2",
        "image" => "meal_images/tacos.jpg",
        "description" => "Mexican street tacos with marinated and spit-grilled pork, pineapple, onions, and cilantro.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 138,
        "restaurant_id" => 35,
        "name" => "Tacos al Pastor 3",
        "image" => "meal_images/tacos.jpg",
        "description" => "Mexican street tacos with marinated and spit-grilled pork, pineapple, onions, and cilantro.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 139,
        "restaurant_id" => 35,
        "name" => "Tacos al Pastor 4",
        "image" => "meal_images/tacos.jpg",
        "description" => "Mexican street tacos with marinated and spit-grilled pork, pineapple, onions, and cilantro.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 140,
        "restaurant_id" => 36,
        "name" => "Ratatouille 1",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 141,
        "restaurant_id" => 36,
        "name" => "Ratatouille 2",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 142,
        "restaurant_id" => 36,
        "name" => "Ratatouille 3",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 143,
        "restaurant_id" => 36,
        "name" => "Ratatouille 4",
        "image" => "meal_images/ratatouille.jpg",
        "description" => "A French Provençal vegetable dish consisting of zucchini, tomatoes, eggplant, and bell peppers, seasoned with herbs. A delightful vegetarian option.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 144,
        "restaurant_id" => 37,
        "name" => "Pizza 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 145,
        "restaurant_id" => 37,
        "name" => "Pizza 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 146,
        "restaurant_id" => 37,
        "name" => "Pizza 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 147,
        "restaurant_id" => 37,
        "name" => "Pizza 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 148,
        "restaurant_id" => 38,
        "name" => "Hamburger 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 149,
        "restaurant_id" => 38,
        "name" => "Hamburger 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 150,
        "restaurant_id" => 38,
        "name" => "Hamburger 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 151,
        "restaurant_id" => 38,
        "name" => "Hamburger 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 152,
        "restaurant_id" => 39,
        "name" => "Maki Sushi 1",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi rolls with various ingredients such as fish, vegetables, and rice wrapped in seaweed.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 153,
        "restaurant_id" => 39,
        "name" => "Maki Sushi 2",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi rolls with various ingredients such as fish, vegetables, and rice wrapped in seaweed.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 154,
        "restaurant_id" => 39,
        "name" => "Maki Sushi 3",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi rolls with various ingredients such as fish, vegetables, and rice wrapped in seaweed.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 155,
        "restaurant_id" => 39,
        "name" => "Maki Sushi 4",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi rolls with various ingredients such as fish, vegetables, and rice wrapped in seaweed.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 156,
        "restaurant_id" => 40,
        "name" => "Gelato 1",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 157,
        "restaurant_id" => 40,
        "name" => "Gelato 2",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 158,
        "restaurant_id" => 40,
        "name" => "Gelato 3",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 159,
        "restaurant_id" => 40,
        "name" => "Gelato 4",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 160,
        "restaurant_id" => 41,
        "name" => "Pasta Carbonara 1",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "An Italian pasta dish from Rome made with eggs, cheese (Pecorino Romano), pancetta, and black pepper.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 161,
        "restaurant_id" => 41,
        "name" => "Pasta Carbonara 2",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "An Italian pasta dish from Rome made with eggs, cheese (Pecorino Romano), pancetta, and black pepper.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 162,
        "restaurant_id" => 41,
        "name" => "Pasta Carbonara 3",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "An Italian pasta dish from Rome made with eggs, cheese (Pecorino Romano), pancetta, and black pepper.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 163,
        "restaurant_id" => 41,
        "name" => "Pasta Carbonara 4",
        "image" => "meal_images/Spaghetti_alla_Carbonara.jpg",
        "description" => "An Italian pasta dish from Rome made with eggs, cheese (Pecorino Romano), pancetta, and black pepper.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 164,
        "restaurant_id" => 42,
        "name" => "Chicken Alfredo 1",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta topped with creamy Alfredo sauce and grilled chicken breast.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 165,
        "restaurant_id" => 42,
        "name" => "Chicken Alfredo 2",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta topped with creamy Alfredo sauce and grilled chicken breast.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 166,
        "restaurant_id" => 42,
        "name" => "Chicken Alfredo 3",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta topped with creamy Alfredo sauce and grilled chicken breast.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 167,
        "restaurant_id" => 42,
        "name" => "Chicken Alfredo 4",
        "image" => "meal_images/alfredo.jpg",
        "description" => "Fettuccine pasta topped with creamy Alfredo sauce and grilled chicken breast.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 168,
        "restaurant_id" => 43,
        "name" => "Shrimp Scampi 1",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Linguine pasta with shrimp, garlic, white wine, and lemon butter sauce.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 169,
        "restaurant_id" => 43,
        "name" => "Shrimp Scampi 2",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Linguine pasta with shrimp, garlic, white wine, and lemon butter sauce.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 170,
        "restaurant_id" => 43,
        "name" => "Shrimp Scampi 3",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Linguine pasta with shrimp, garlic, white wine, and lemon butter sauce.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 171,
        "restaurant_id" => 43,
        "name" => "Shrimp Scampi 4",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Linguine pasta with shrimp, garlic, white wine, and lemon butter sauce.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 172,
        "restaurant_id" => 44,
        "name" => "Vegetarian Pizza 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Pizza topped with a variety of fresh vegetables and melted cheese.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 173,
        "restaurant_id" => 44,
        "name" => "Vegetarian Pizza 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Pizza topped with a variety of fresh vegetables and melted cheese.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 174,
        "restaurant_id" => 44,
        "name" => "Vegetarian Pizza 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Pizza topped with a variety of fresh vegetables and melted cheese.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 175,
        "restaurant_id" => 44,
        "name" => "Vegetarian Pizza 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Pizza topped with a variety of fresh vegetables and melted cheese.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 176,
        "restaurant_id" => 45,
        "name" => "Chicken Quesadilla 1",
        "image" => "meal_images/quesadilla.jpg",
        "description" => "Tortilla filled with grilled chicken, cheese, and various toppings, served with salsa and sour cream.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 177,
        "restaurant_id" => 45,
        "name" => "Chicken Quesadilla 2",
        "image" => "meal_images/quesadilla.jpg",
        "description" => "Tortilla filled with grilled chicken, cheese, and various toppings, served with salsa and sour cream.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 178,
        "restaurant_id" => 45,
        "name" => "Chicken Quesadilla 3",
        "image" => "meal_images/quesadilla.jpg",
        "description" => "Tortilla filled with grilled chicken, cheese, and various toppings, served with salsa and sour cream.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 179,
        "restaurant_id" => 45,
        "name" => "Chicken Quesadilla 4",
        "image" => "meal_images/quesadilla.jpg",
        "description" => "Tortilla filled with grilled chicken, cheese, and various toppings, served with salsa and sour cream.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 180,
        "restaurant_id" => 46,
        "name" => "Garlic Butter Shrimp 1",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Shrimp cooked in a flavorful garlic butter sauce, served with rice or pasta.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 181,
        "restaurant_id" => 46,
        "name" => "Garlic Butter Shrimp 2",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Shrimp cooked in a flavorful garlic butter sauce, served with rice or pasta.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 182,
        "restaurant_id" => 46,
        "name" => "Garlic Butter Shrimp 3",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Shrimp cooked in a flavorful garlic butter sauce, served with rice or pasta.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 183,
        "restaurant_id" => 46,
        "name" => "Garlic Butter Shrimp 4",
        "image" => "meal_images/seafood_meal.jpg",
        "description" => "Shrimp cooked in a flavorful garlic butter sauce, served with rice or pasta.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 184,
        "restaurant_id" => 47,
        "name" => "Caprese Salad 1",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh salad made with tomatoes, mozzarella cheese, basil, and balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 185,
        "restaurant_id" => 47,
        "name" => "Caprese Salad 2",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh salad made with tomatoes, mozzarella cheese, basil, and balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 186,
        "restaurant_id" => 47,
        "name" => "Caprese Salad 3",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh salad made with tomatoes, mozzarella cheese, basil, and balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 187,
        "restaurant_id" => 47,
        "name" => "Caprese Salad 4",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh salad made with tomatoes, mozzarella cheese, basil, and balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 188,
        "restaurant_id" => 48,
        "name" => "Margherita Pizza 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 189,
        "restaurant_id" => 48,
        "name" => "Margherita Pizza 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 190,
        "restaurant_id" => 48,
        "name" => "Margherita Pizza 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 191,
        "restaurant_id" => 48,
        "name" => "Margherita Pizza 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 192,
        "restaurant_id" => 49,
        "name" => "Tiramisù 1",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 193,
        "restaurant_id" => 49,
        "name" => "Tiramisù 2",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 194,
        "restaurant_id" => 49,
        "name" => "Tiramisù 3",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 195,
        "restaurant_id" => 49,
        "name" => "Tiramisù 4",
        "image" => "meal_images/Tiramisù.jpg",
        "description" => "Un dolce italiano composto da strati di savoiardi inzuppati nel caffè, alternati a una crema di mascarpone, uova e zucchero, spolverato con cacao in polvere",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 196,
        "restaurant_id" => 50,
        "name" => "Noodle 1",
        "image" => "meal_images/thai.jpg",
        "description" => "Zuppa giapponese con noodle, brodo di carne, carne di maiale, cipolla verde, alga nori e uovo sodo. Una delizia per gli amanti della cucina asiatica.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 197,
        "restaurant_id" => 50,
        "name" => "Noodle 2",
        "image" => "meal_images/thai.jpg",
        "description" => "Zuppa giapponese con noodle, brodo di carne, carne di maiale, cipolla verde, alga nori e uovo sodo. Una delizia per gli amanti della cucina asiatica.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 198,
        "restaurant_id" => 50,
        "name" => "Noodle 3",
        "image" => "meal_images/thai.jpg",
        "description" => "Zuppa giapponese con noodle, brodo di carne, carne di maiale, cipolla verde, alga nori e uovo sodo. Una delizia per gli amanti della cucina asiatica.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 199,
        "restaurant_id" => 50,
        "name" => "Noodle 4",
        "image" => "meal_images/thai.jpg",
        "description" => "Zuppa giapponese con noodle, brodo di carne, carne di maiale, cipolla verde, alga nori e uovo sodo. Una delizia per gli amanti della cucina asiatica.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 200,
        "restaurant_id" => 51,
        "name" => "Mushroom Risotto 1",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 201,
        "restaurant_id" => 51,
        "name" => "Mushroom Risotto 2",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 202,
        "restaurant_id" => 51,
        "name" => "Mushroom Risotto 3",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 203,
        "restaurant_id" => 51,
        "name" => "Mushroom Risotto 4",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 204,
        "restaurant_id" => 52,
        "name" => "Sushi 1",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi roll with avocado, cucumber, and carrot, served with soy sauce and pickled ginger.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 205,
        "restaurant_id" => 52,
        "name" => "Sushi 2",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi roll with avocado, cucumber, and carrot, served with soy sauce and pickled ginger.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 206,
        "restaurant_id" => 52,
        "name" => "Sushi 3",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi roll with avocado, cucumber, and carrot, served with soy sauce and pickled ginger.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 207,
        "restaurant_id" => 52,
        "name" => "Sushi 4",
        "image" => "meal_images/Sushi_assortito.jpg",
        "description" => "Sushi roll with avocado, cucumber, and carrot, served with soy sauce and pickled ginger.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 208,
        "restaurant_id" => 53,
        "name" => "Hamburger 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 209,
        "restaurant_id" => 53,
        "name" => "Hamburger 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 210,
        "restaurant_id" => 53,
        "name" => "Hamburger 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 211,
        "restaurant_id" => 53,
        "name" => "Hamburger 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 212,
        "restaurant_id" => 54,
        "name" => "Shrimp Scampi Pasta 1",
        "image" => "meal_images/shrimp_pasta.jpg",
        "description" => "Pasta dish with succulent shrimp, garlic, lemon, and white wine sauce.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 213,
        "restaurant_id" => 54,
        "name" => "Shrimp Scampi Pasta 2",
        "image" => "meal_images/shrimp_pasta.jpg",
        "description" => "Pasta dish with succulent shrimp, garlic, lemon, and white wine sauce.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 214,
        "restaurant_id" => 54,
        "name" => "Shrimp Scampi Pasta 3",
        "image" => "meal_images/shrimp_pasta.jpg",
        "description" => "Pasta dish with succulent shrimp, garlic, lemon, and white wine sauce.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 215,
        "restaurant_id" => 54,
        "name" => "Shrimp Scampi Pasta 4",
        "image" => "meal_images/shrimp_pasta.jpg",
        "description" => "Pasta dish with succulent shrimp, garlic, lemon, and white wine sauce.",
        "price" => 24.00,
        "available" => 1,
    ],
    [
        "id" => 216,
        "restaurant_id" => 55,
        "name" => "Chicken Tikka Masala 1",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 217,
        "restaurant_id" => 55,
        "name" => "Chicken Tikka Masala 2",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 218,
        "restaurant_id" => 55,
        "name" => "Chicken Tikka Masala 3",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 219,
        "restaurant_id" => 55,
        "name" => "Chicken Tikka Masala 4",
        "image" => "meal_images/Chicken_Tikka_Masala.jpg",
        "description" => "Pezzi di pollo marinati in una miscela di yogurt e spezie, quindi cotti in un forno tandoor e serviti in una salsa cremosa di pomodoro e spezie.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 220,
        "restaurant_id" => 56,
        "name" => "Gelato 1",
        "image" => "meal_images/Anatra_alla_pechinese.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 221,
        "restaurant_id" => 56,
        "name" => "Gelato 2",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 222,
        "restaurant_id" => 56,
        "name" => "Gelato 3",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 223,
        "restaurant_id" => 56,
        "name" => "Gelato 4",
        "image" => "meal_images/icecream.jpg",
        "description" => "Il gelato alla fragola incanta i sensi con la sua cremosità vellutata e il gusto fresco e fruttato delle fragole appena raccolte.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 224,
        "restaurant_id" => 57,
        "name" => "Hamburger 1",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 10.00,
        "available" => 1,
    ],
    [
        "id" => 225,
        "restaurant_id" => 57,
        "name" => "Hamburger 2",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 10.00,
        "available" => 1,
    ],
    [
        "id" => 226,
        "restaurant_id" => 57,
        "name" => "Hamburger 3",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 10.00,
        "available" => 1,
    ],
    [
        "id" => 227,
        "restaurant_id" => 57,
        "name" => "Hamburger 4",
        "image" => "meal_images/Hamburger_Classico.jpg",
        "description" => "Un hamburger americano classico con un pattino di manzo grigliato, lattuga, pomodoro, cetrioli, cipolla e ketchup, servito su un panino con semi di sesamo.",
        "price" => 10.00,
        "available" => 1,
    ],
    [
        "id" => 228,
        "restaurant_id" => 58,
        "name" => "Caprese Salad 1",
        "image" => "meal_images/caprese.jpg",
        "description" => "Classic Italian salad with fresh tomatoes, mozzarella, basil, and balsamic glaze.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 229,
        "restaurant_id" => 58,
        "name" => "Caprese Salad 2",
        "image" => "meal_images/caprese.jpg",
        "description" => "Classic Italian salad with fresh tomatoes, mozzarella, basil, and balsamic glaze.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 230,
        "restaurant_id" => 58,
        "name" => "Caprese Salad 3",
        "image" => "meal_images/caprese.jpg",
        "description" => "Classic Italian salad with fresh tomatoes, mozzarella, basil, and balsamic glaze.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 231,
        "restaurant_id" => 58,
        "name" => "Caprese Salad 4",
        "image" => "meal_images/caprese.jpg",
        "description" => "Classic Italian salad with fresh tomatoes, mozzarella, basil, and balsamic glaze.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 232,
        "restaurant_id" => 59,
        "name" => "Pizza 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 233,
        "restaurant_id" => 59,
        "name" => "Pizza 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 234,
        "restaurant_id" => 59,
        "name" => "Pizza 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 235,
        "restaurant_id" => 59,
        "name" => "Pizza 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 236,
        "restaurant_id" => 60,
        "name" => "Gyudon 1",
        "image" => "meal_images/thai.jpg",
        "description" => "A Japanese dish consisting of thinly sliced beef, onions, and other ingredients simmered in a mildly sweet soy sauce-based broth, served over rice.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 237,
        "restaurant_id" => 60,
        "name" => "Gyudon 2",
        "image" => "meal_images/thai.jpg",
        "description" => "A Japanese dish consisting of thinly sliced beef, onions, and other ingredients simmered in a mildly sweet soy sauce-based broth, served over rice.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 238,
        "restaurant_id" => 60,
        "name" => "Gyudon 3",
        "image" => "meal_images/thai.jpg",
        "description" => "A Japanese dish consisting of thinly sliced beef, onions, and other ingredients simmered in a mildly sweet soy sauce-based broth, served over rice.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 239,
        "restaurant_id" => 60,
        "name" => "Gyudon 4",
        "image" => "meal_images/thai.jpg",
        "description" => "A Japanese dish consisting of thinly sliced beef, onions, and other ingredients simmered in a mildly sweet soy sauce-based broth, served over rice.",
        "price" => 20.00,
        "available" => 1,
    ],
    [
        "id" => 240,
        "restaurant_id" => 61,
        "name" => "Mushroom Risotto 1",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 241,
        "restaurant_id" => 61,
        "name" => "Mushroom Risotto 2",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 242,
        "restaurant_id" => 61,
        "name" => "Mushroom Risotto 3",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 243,
        "restaurant_id" => 61,
        "name" => "Mushroom Risotto 4",
        "image" => "meal_images/risotto.jpg",
        "description" => "Creamy risotto cooked with assorted mushrooms and Parmesan cheese.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 244,
        "restaurant_id" => 62,
        "name" => "Banh Mi 1",
        "image" => "meal_images/bahn.jpg",
        "description" => "A Vietnamese sandwich consisting of a baguette filled with a variety of ingredients, typically including meat, pickled vegetables, and condiments.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 245,
        "restaurant_id" => 62,
        "name" => "Banh Mi 2",
        "image" => "meal_images/bahn.jpg",
        "description" => "A Vietnamese sandwich consisting of a baguette filled with a variety of ingredients, typically including meat, pickled vegetables, and condiments.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 246,
        "restaurant_id" => 62,
        "name" => "Banh Mi 3",
        "image" => "meal_images/bahn.jpg",
        "description" => "A Vietnamese sandwich consisting of a baguette filled with a variety of ingredients, typically including meat, pickled vegetables, and condiments.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 247,
        "restaurant_id" => 62,
        "name" => "Banh Mi 4",
        "image" => "meal_images/bahn.jpg",
        "description" => "A Vietnamese sandwich consisting of a baguette filled with a variety of ingredients, typically including meat, pickled vegetables, and condiments.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 248,
        "restaurant_id" => 63,
        "name" => "BBQ Pulled Pork Sandwich 1",
        "image" => "meal_images/pork.jpg",
        "description" => "Slow-cooked pulled pork in BBQ sauce, served in a soft bun with coleslaw.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 249,
        "restaurant_id" => 63,
        "name" => "BBQ Pulled Pork Sandwich 2",
        "image" => "meal_images/pork.jpg",
        "description" => "Slow-cooked pulled pork in BBQ sauce, served in a soft bun with coleslaw.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 250,
        "restaurant_id" => 63,
        "name" => "BBQ Pulled Pork Sandwich 3",
        "image" => "meal_images/pork.jpg",
        "description" => "Slow-cooked pulled pork in BBQ sauce, served in a soft bun with coleslaw.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 251,
        "restaurant_id" => 63,
        "name" => "BBQ Pulled Pork Sandwich 4",
        "image" => "meal_images/pork.jpg",
        "description" => "Slow-cooked pulled pork in BBQ sauce, served in a soft bun with coleslaw.",
        "price" => 15.00,
        "available" => 1,
    ],
    [
        "id" => 252,
        "restaurant_id" => 64,
        "name" => "Pizza Margherita 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 253,
        "restaurant_id" => 64,
        "name" => "Pizza Margherita 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 254,
        "restaurant_id" => 64,
        "name" => "Pizza Margherita 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 255,
        "restaurant_id" => 64,
        "name" => "Pizza Margherita 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Una pizza classica italiana con salsa di pomodoro, mozzarella di bufala, basilico fresco, sale e olio d'oliva.",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 256,
        "restaurant_id" => 65,
        "name" => "Margherita Pizza 1",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 257,
        "restaurant_id" => 65,
        "name" => "Margherita Pizza 2",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 258,
        "restaurant_id" => 65,
        "name" => "Margherita Pizza 3",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 259,
        "restaurant_id" => 65,
        "name" => "Margherita Pizza 4",
        "image" => "meal_images/Pizza_Margherita.jpg",
        "description" => "Classic pizza with tomato sauce, fresh mozzarella, basil, and a drizzle of olive oil.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 260,
        "restaurant_id" => 66,
        "name" => "Moussaka 1",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Capolavoro culinario che unisce strati di melanzane grigliate, carne macinata di agnello o manzo saziamente speziata e una morbida besciamella.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 261,
        "restaurant_id" => 66,
        "name" => "Moussaka 2",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Capolavoro culinario che unisce strati di melanzane grigliate, carne macinata di agnello o manzo saziamente speziata e una morbida besciamella.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 262,
        "restaurant_id" => 66,
        "name" => "Moussaka 3",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Capolavoro culinario che unisce strati di melanzane grigliate, carne macinata di agnello o manzo saziamente speziata e una morbida besciamella.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 263,
        "restaurant_id" => 66,
        "name" => "Moussaka 4",
        "image" => "meal_images/Moussaka.jpg",
        "description" => "Capolavoro culinario che unisce strati di melanzane grigliate, carne macinata di agnello o manzo saziamente speziata e una morbida besciamella.",
        "price" => 18.00,
        "available" => 1,
    ],
    [
        "id" => 264,
        "restaurant_id" => 67,
        "name" => "Caprese Salad 1",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 265,
        "restaurant_id" => 67,
        "name" => "Caprese Salad 2",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 266,
        "restaurant_id" => 67,
        "name" => "Caprese Salad 3",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 267,
        "restaurant_id" => 67,
        "name" => "Caprese Salad 4",
        "image" => "meal_images/caprese.jpg",
        "description" => "Fresh tomatoes, mozzarella, and basil drizzled with balsamic glaze.",
        "price" => 12.00,
        "available" => 1,
    ],
    [
        "id" => 268,
        "restaurant_id" => 68,
        "name" => "Enchiladas 1",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Tortillas di mais avvolte attorno a un ripieno succulento di carne, pollo o fagioli, il tutto abbracciato da una salsa ricca di peperoncino, pomodoro e spezie",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 269,
        "restaurant_id" => 68,
        "name" => "Enchiladas 2",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Tortillas di mais avvolte attorno a un ripieno succulento di carne, pollo o fagioli, il tutto abbracciato da una salsa ricca di peperoncino, pomodoro e spezie",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 270,
        "restaurant_id" => 68,
        "name" => "Enchiladas 3",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Tortillas di mais avvolte attorno a un ripieno succulento di carne, pollo o fagioli, il tutto abbracciato da una salsa ricca di peperoncino, pomodoro e spezie",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 271,
        "restaurant_id" => 68,
        "name" => "Enchiladas 4",
        "image" => "meal_images/Enchiladas.jpg",
        "description" => "Tortillas di mais avvolte attorno a un ripieno succulento di carne, pollo o fagioli, il tutto abbracciato da una salsa ricca di peperoncino, pomodoro e spezie",
        "price" => 22.00,
        "available" => 1,
    ],
    [
        "id" => 272,
        "restaurant_id" => 69,
        "name" => "Gnocchi al Pesto 1",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 273,
        "restaurant_id" => 69,
        "name" => "Gnocchi al Pesto 2",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 274,
        "restaurant_id" => 69,
        "name" => "Gnocchi al Pesto 3",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 275,
        "restaurant_id" => 69,
        "name" => "Gnocchi al Pesto 4",
        "image" => "meal_images/gnocchi.jpg",
        "description" => "Gnocchi di patate serviti con pesto alla genovese, pinoli e formaggio grattugiato. Un piatto italiano ricco di sapore.",
        "price" => 16.00,
        "available" => 1,
    ],
    [
        "id" => 276,
        "restaurant_id" => 70,
        "name" => "Pancakes 1",
        "image" => "meal_images/pancakes.jpg",
        "description" => "Pancakes soffici serviti con sciroppo d'acero, frutti di bosco e panna montata. Una colazione classica e deliziosa.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 277,
        "restaurant_id" => 70,
        "name" => "Pancakes 2",
        "image" => "meal_images/pancakes.jpg",
        "description" => "Pancakes soffici serviti con sciroppo d'acero, frutti di bosco e panna montata. Una colazione classica e deliziosa.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 278,
        "restaurant_id" => 70,
        "name" => "Pancakes 3",
        "image" => "meal_images/pancakes.jpg",
        "description" => "Pancakes soffici serviti con sciroppo d'acero, frutti di bosco e panna montata. Una colazione classica e deliziosa.",
        "price" => 14.00,
        "available" => 1,
    ],
    [
        "id" => 279,
        "restaurant_id" => 70,
        "name" => "Pancakes 4",
        "image" => "meal_images/pancakes.jpg",
        "description" => "Pancakes soffici serviti con sciroppo d'acero, frutti di bosco e panna montata. Una colazione classica e deliziosa.",
        "price" => 14.00,
        "available" => 1,
    ],
];
