<?php
return [
    [
        "id"          => 1,
        "payment"        => "Con carta di credito",
        "date"        => "2024-02-17",
        "client_email"       => "clientemail@gmail.com",
        "client_name" => "Mario Rossi",
        "delivery_address"       => "Via Marco Polo , 15",
        "delivery_time"   => "2024-02-17 20:30:00",
        "client_phone"   => "1234567890",
    ],
    [
        "id"          => 2,
        "payment"        => "Contanti alla consegna",
        "date"        => "2024-02-18",
        "client_email"       => "clientemail@gmail.com",
        "client_name" => "Giuseppe Verdi",
        "delivery_address"       => "Via Napoli , 12",
        "delivery_time"   => "2024-02-17 17:30:00",
        "client_phone"   => "0123456789",
    ],
    [
        "id"          => 3,
        "payment"        => "Contanti alla consegna",
        "date"        => "2024-02-18",
        "client_email"       => "clientemail@gmail.com",
        "client_name" => "Giuseppe Verdi",
        "delivery_address"       => "Via Napoli , 12",
        "delivery_time"   => "2024-02-17 17:30:00",
        "client_phone"   => "0123456789",
    ],
    [
        "id"          => 4,
        "payment"        => "Contanti alla consegna",
        "date"        => "2024-02-18",
        "client_email"       => "clientemail@gmail.com",
        "client_name" => "Giuseppe Verdi",
        "delivery_address"       => "Via Napoli , 12",
        "delivery_time"   => "2024-02-17 17:30:00",
        "client_phone"   => "0123456789",
    ],
    // [
    //     "id"          => 5,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 6,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 7,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 8,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 9,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 10,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 11,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 12,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 13,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 14,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 15,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 16,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 17,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 17,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 18,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 19,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
    // [
    //     "id"          => 20,
    //     "payment"        => "Contanti alla consegna",
    //     "date"        => "2024-02-18",
    //     "client_email"       => "clientemail@gmail.com",
    //     "client_name" => "Giuseppe Verdi",
    //     "delivery_address"       => "Via Napoli , 12",
    //     "delivery_time"   => "2024-02-17 17:30:00",
    //  
    //     "client_phone"   => "0123456789",
    // ],
];