<?php

return [
    [
        "id"              => 1,
        "user_id"         => 1,
        "restaurant_name" => "Trattoria La Piazza",
        "image"           => "restaurant_images/Trattoria_La_Piazza.jpg",
        "street"          => "via Trattoria La Piazza",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678921",
    ],
    [
        "id"              => 2,
        "user_id"         => 2,
        "restaurant_name" => "Grande Muraglia",
        "image"           => "restaurant_images/Grande_Muraglia.png",
        "street"          => "via Grande Muraglia",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678922",
    ],
    [
        "id"              => 3,
        "user_id"         => 3,
        "restaurant_name" => " Sakura Sushi Bar",
        "image"           => "restaurant_images/Sakura_Sushi_Bar.jpg",
        "street"          => "via  Sakura Sushi Bar",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678923",
    ],
    [
        "id"              => 4,
        "user_id"         => 4,
        "restaurant_name" => "El Ranchito Mexicano",
        "image"           => "restaurant_images/El_Ranchito_Mexicano.jpg",
        "street"          => "via El Ranchito Mexicano",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678924",
    ],
    [
        "id"              => 5,
        "user_id"         => 5,
        "restaurant_name" => "Olimpo Taverna",
        "image"           => "restaurant_images/Olimpo_Taverna.png",
        "street"          => "via Olimpo Taverna",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678925",
    ],
    [
        "id"              => 6,
        "user_id"         => 6,
        "restaurant_name" => "Taj Mahal Curry House",
        "image"           => "restaurant_images/Taj_Mahal_Curry_House.jpg",
        "street"          => "via Taj Mahal Curry House",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678926",
    ],
    [
        "id"              => 7,
        "user_id"         => 7,
        "restaurant_name" => "La Bella Napoli",
        "image"           => "restaurant_images/La_Bella_Napoli.png",
        "street"          => "via La Bella Napoli",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678927",
    ],
    [
        "id"              => 8,
        "user_id"         => 8,
        "restaurant_name" => "Grill & Chill Burger Joint",
        "image"           => "restaurant_images/Grill_&_Chill_Burger_Joint.jpg",
        "street"          => "via Grill & Chill Burger Joint",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678980",
    ],
    [
        "id"              => 9,
        "user_id"         => 9,
        "restaurant_name" => "Pacifico Poke Bowl",
        "image"           => "restaurant_images/Pacifico_Poke_Bowl.jpg",
        "street"          => "via Pacifico Poke Bowl",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678929",
    ],
    [
        "id"              => 10,
        "user_id"         =>10,
        "restaurant_name" => "Sweet Delights Bakery",
        "image"           => "restaurant_images/Sweet_Delights_Bakery.jpg",
        "street"          => "via Sweet Delights Bakery",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847648970",
    ],
];
