<?php

return [
    [
        "id"              => 1,
        "restaurant_name" => "italiano",
        "image"           => "italiano",
        "street"          => "via italiano",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678921",
    ],
    [
        "id"              => 2,
        "restaurant_name" => "cinese",
        "image"           => "cinese",
        "street"          => "via cinese",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678922",
    ],
    [
        "id"              => 3,
        "restaurant_name" => "giapponese",
        "image"           => "giapponese",
        "street"          => "via giapponese",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678923",
    ],
    [
        "id"              => 4,
        "restaurant_name" => "messicano",
        "image"           => "messicano",
        "street"          => "via messicano",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678924",
    ],
    [
        "id"              => 5,
        "restaurant_name" => "greco",
        "image"           => "greco",
        "street"          => "via greco",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678925",
    ],
    [
        "id"              => 6,
        "restaurant_name" => "indiano",
        "image"           => "indiano",
        "street"          => "via indiano",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678926",
    ],
    [
        "id"              => 7,
        "restaurant_name" => "pizza",
        "image"           => "pizza",
        "street"          => "via pizza",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678927",
    ],
    [
        "id"              => 8,
        "restaurant_name" => "hamburgher",
        "image"           => "hamburgher",
        "street"          => "via hamburgher",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678980",
    ],
    [
        "id"              => 9,
        "restaurant_name" => "poke",
        "image"           => "poke",
        "street"          => "via poke",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847678929",
    ],
    [
        "id"              => 10,
        "restaurant_name" => "dolci",
        "image"           => "dolci",
        "street"          => "via dolci",
        "time_open"       => '08:00:00',
        "time_close"      => '21:00:00',
        "piva_user"       => "04847648970",
    ],
];
