<?php 

return [
    [
        "id"       => 1,
        "name"     => "pippo",
        "email"    => "pippo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 2,
        "name"     => "pluto",
        "email"    => "pluto@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 3,
        "name"     => "paperino",
        "email"    => "paperino@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 4,
        "name"     => "giuseppe",
        "email"    => "giuseppe@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 5,
        "name"     => "anna",
        "email"    => "anna@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 6,
        "name"     => "carlo",
        "email"    => "carlo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 7,
        "name"     => "elena",
        "email"    => "elena@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 8,
        "name"     => "francesco",
        "email"    => "francesco@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 9,
        "name"     => "luisa",
        "email"    => "luisa@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 10,
        "name"     => "mario",
        "email"    => "mario@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 11,
        "name"     => "francesca",
        "email"    => "francesca@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 12,
        "name"     => "luca",
        "email"    => "luca@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 13,
        "name"     => "madalina",
        "email"    => "madalina@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 14,
        "name"     => "valentina",
        "email"    => "valentina@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 15,
        "name"     => "marco",
        "email"    => "marco@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 16,
        "name"     => "pierluigi",
        "email"    => "pierluigi@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 17,
        "name"     => "daniel",
        "email"    => "daniel@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 18,
        "name"     => "cesare",
        "email"    => "cesare@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 19,
        "name"     => "ludovica",
        "email"    => "ludovica@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 20,
        "name"     => "andrea",
        "email"    => "andrea@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 21,
        "name"     => "monica",
        "email"    => "monica@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 22,
        "name"     => "gianmarco",
        "email"    => "gianmarco@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 23,
        "name"     => "angelo",
        "email"    => "angelo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 24,
        "name"     => "federico",
        "email"    => "federico@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 25,
        "name"     => "matteo",
        "email"    => "matteo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 26,
        "name"     => "lorenzo",
        "email"    => "lorenzo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 27,
        "name"     => "fabiana",
        "email"    => "fabiana@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 28,
        "name"     => "katia",
        "email"    => "katia@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 29,
        "name"     => "orlando",
        "email"    => "orlando@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 30,
        "name"     => "alessandro",
        "email"    => "alessandro@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 31,
        "name"     => "paolo",
        "email"    => "paolo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 32,
        "name"     => "michele",
        "email"    => "michele@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 33,
        "name"     => "aldo",
        "email"    => "aldo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 34,
        "name"     => "giovanni",
        "email"    => "giovanni@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 35,
        "name"     => "giacomo",
        "email"    => "giacomo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 36,
        "name"     => "claudia",
        "email"    => "claudia@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 37,
        "name"     => "giuliana",
        "email"    => "giuliana@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 38,
        "name"     => "magda",
        "email"    => "magda@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 39,
        "name"     => "furio",
        "email"    => "furio@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 40,
        "name"     => "alberto",
        "email"    => "alberto@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 41,
        "name"     => "marcello",
        "email"    => "marcello@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 42,
        "name"     => "paola",
        "email"    => "paola@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 43,
        "name"     => "luigi",
        "email"    => "luigi@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 44,
        "name"     => "serena",
        "email"    => "serena@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 45,
        "name"     => "kristian",
        "email"    => "kristian@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 46,
        "name"     => "enrico",
        "email"    => "enrico@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 47,
        "name"     => "giordano",
        "email"    => "giordano@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 48,
        "name"     => "ugo",
        "email"    => "ugo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 49,
        "name"     => "marcovaldo",
        "email"    => "marcovaldo@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 50,
        "name"     => "olivia",
        "email"    => "olivia@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 51,
        "name"     => "ettore",
        "email"    => "ettore@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 52,
        "name"     => "carla",
        "email"    => "carla@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 53,
        "name"     => "cristiano",
        "email"    => "cristiano@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 54,
        "name"     => "fabrizio",
        "email"    => "fabrizio@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 55,
        "name"     => "augusto",
        "email"    => "augusto@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 56,
        "name"     => "carola",
        "email"    => "carola@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 57,
        "name"     => "matilde",
        "email"    => "matilde@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 58,
        "name"     => "davide",
        "email"    => "davide@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 59,
        "name"     => "mark",
        "email"    => "mark@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 60,
        "name"     => "gabriele",
        "email"    => "gabriele@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 61,
        "name"     => "umberto",
        "email"    => "umberto@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 62,
        "name"     => "brenda",
        "email"    => "brenda@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 63,
        "name"     => "sara",
        "email"    => "sara@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 64,
        "name"     => "alice",
        "email"    => "alice@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 65,
        "name"     => "elisa",
        "email"    => "elisa@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 66,
        "name"     => "rachel",
        "email"    => "rachel@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 67,
        "name"     => "raymond",
        "email"    => "raymond@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 68,
        "name"     => "beatrice",
        "email"    => "beatrice@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 69,
        "name"     => "virginia",
        "email"    => "virginia@gmail.com",
        "password" => 'password',
    ],
    [
        "id"       => 70,
        "name"     => "edoardo",
        "email"    => "edoardo@gmail.com",
        "password" => 'password',
    ],
];